# Generated by Django 5.1.7 on 2025-04-18 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0021_alter_details_offer_userdetails'),
        ('orders_app', '0003_alter_order_business_user_alter_order_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer_detail_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers_app.details'),
        ),
    ]
