# Generated by Django 5.1.7 on 2025-04-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0004_order_offer_detail_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='offer_detail_id',
        ),
    ]
