# Generated by Django 5.1.7 on 2025-04-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0009_alter_order_offer_detail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='offer_detail_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
