# Generated by Django 5.1.7 on 2025-04-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0003_alter_offer_user_alter_userdetails_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('revisions', models.IntegerField()),
                ('delivery_time_in_days', models.IntegerField()),
                ('price', models.IntegerField()),
                ('features', models.CharField(max_length=200)),
                ('offer_type', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='min_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='details',
            field=models.ManyToManyField(to='offers_app.offerdetails'),
        ),
        migrations.DeleteModel(
            name='OfferDetail',
        ),
    ]
