# Generated by Django 5.1.7 on 2025-04-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0006_remove_offer_min_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetails',
            name='features',
            field=models.JSONField(),
        ),
    ]
