# Generated by Django 5.1.7 on 2025-04-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0008_offer_min_delivery_time_offer_min_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetails',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
