# Generated by Django 5.1.7 on 2025-04-09 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0009_alter_offerdetails_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers_app.offer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='user_details',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offerdetails',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
