# Generated by Django 5.1.7 on 2025-04-09 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0011_alter_offerdetails_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='user_details',
        ),
        migrations.RemoveField(
            model_name='offerdetails',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='offer',
        ),
        migrations.AlterField(
            model_name='offer',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers_app.offerdetails'),
        ),
        migrations.AlterField(
            model_name='offerdetails',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
