# Generated by Django 5.1.7 on 2025-04-09 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0012_remove_offer_user_details_remove_offerdetails_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offers_app.offerdetails'),
        ),
    ]
