# Generated by Django 5.1.7 on 2025-04-09 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0013_alter_offer_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='details',
        ),
        migrations.AddField(
            model_name='offerdetails',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers_app.offer'),
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
