# Generated by Django 5.1.7 on 2025-04-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0014_remove_offer_details_offerdetails_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='details',
            field=models.IntegerField(null=True),
        ),
    ]
