# Generated by Django 5.1.7 on 2025-04-11 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0015_offer_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='min_delivery_time',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='min_price',
        ),
    ]
