# Generated by Django 5.1.7 on 2025-04-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0016_remove_offer_min_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='min_delivery_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='min_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
