# Generated by Django 5.1.7 on 2025-04-12 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0017_offer_min_delivery_time_offer_min_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='details',
        ),
    ]
