# Generated by Django 5.1.7 on 2025-04-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0018_remove_offer_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='details',
            field=models.IntegerField(null=True),
        ),
    ]
