# Generated by Django 5.1.7 on 2025-03-25 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(null=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.CharField(default='2023-10-30T10:00:00Z', max_length=50)),
                ('updated_at', models.CharField(blank=True, max_length=50, null=True)),
                ('business_user', models.OneToOneField(default=7, on_delete=django.db.models.deletion.CASCADE, to='profile_app.profile')),
                ('reviewer', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
