# Generated by Django 5.1.7 on 2025-03-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0002_review_auth_user_alter_review_business_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
